# Generated by Django 3.2.6 on 2021-08-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210806_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSettings',
            fields=[
                ('net_id', models.AutoField(primary_key=True, serialize=False)),
                ('network', models.CharField(max_length=100)),
                ('network_type', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('net_mask', models.CharField(max_length=100)),
                ('gate_way', models.CharField(max_length=100)),
                ('dns_server', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SensorSettings',
            fields=[
                ('sen_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_temp_sen_id', models.CharField(max_length=100)),
                ('ambient_type', models.CharField(max_length=100)),
                ('sensor_id', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=100)),
                ('api_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
