# Generated by Django 3.2.6 on 2021-08-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dashboard_setpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='id',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='dashboard_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
